from __future__ import annotations

import io
import tempfile
from pathlib import Path

import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import streamlit as st

from echopulse.audio import load_audio
from echopulse.config import load_config
from echopulse.features import extract_mfcc_features
from echopulse.modeling import load_bundle

st.set_page_config(page_title="EchoPulse", page_icon="🫁", layout="wide")


@st.cache_resource(show_spinner=False)
def get_config_and_bundle(config_path: str, bundle_path: str):
    config = load_config(config_path)
    bundle = load_bundle(bundle_path)
    return config, bundle


def load_uploaded_signal(uploaded_file, sample_rate: int, duration_seconds: int) -> np.ndarray:
    suffix = Path(uploaded_file.name).suffix or ".wav"
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
        tmp.write(uploaded_file.getbuffer())
        tmp_path = tmp.name
    return load_audio(tmp_path, sample_rate=sample_rate, duration_seconds=duration_seconds)


def predict_from_signal(signal: np.ndarray, config: dict, bundle, model_name: str):
    audio_cfg = config["audio"]
    features = extract_mfcc_features(
        signal,
        sample_rate=audio_cfg["sample_rate"],
        n_mfcc=audio_cfg["n_mfcc"],
        n_fft=audio_cfg["n_fft"],
        hop_length=audio_cfg["hop_length"],
    ).reshape(1, -1)

    model = {
        "Random Forest": bundle.rf_pipeline,
        "SVM": bundle.svm_pipeline,
        "Ensemble": bundle.ensemble_pipeline,
    }[model_name]

    pred_encoded = model.predict(features)[0]
    pred_label = bundle.label_encoder.inverse_transform([pred_encoded])[0]

    probabilities = None
    if hasattr(model, "predict_proba"):
        probabilities = model.predict_proba(features)[0]

    return pred_label, probabilities, features


def make_waveform_plot(signal: np.ndarray, sample_rate: int):
    fig, ax = plt.subplots(figsize=(10, 3))
    librosa.display.waveshow(signal, sr=sample_rate, ax=ax)
    ax.set_title("Waveform")
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Amplitude")
    fig.tight_layout()
    return fig


def make_spectrogram_plot(signal: np.ndarray, sample_rate: int):
    stft = librosa.stft(signal)
    db = librosa.amplitude_to_db(np.abs(stft), ref=np.max)
    fig, ax = plt.subplots(figsize=(10, 4))
    img = librosa.display.specshow(db, sr=sample_rate, x_axis="time", y_axis="hz", ax=ax)
    ax.set_title("Spectrogram")
    fig.colorbar(img, ax=ax, format="%+2.0f dB")
    fig.tight_layout()
    return fig


def make_probability_chart(labels: list[str], probabilities: np.ndarray):
    df = pd.DataFrame({"Label": labels, "Probability": probabilities}).sort_values(
        "Probability", ascending=False
    )
    st.bar_chart(df.set_index("Label"))
    return df


def main() -> None:
    st.title("EchoPulse Web App")
    st.caption("Upload a lung or heart sound recording and run EchoPulse inference.")

    with st.sidebar:
        st.header("Settings")
        config_path = st.text_input("Config path", value="config.yaml")
        bundle_path = st.text_input("Model bundle path", value="models/model_bundle.joblib")
        model_name = st.selectbox("Prediction model", ["Ensemble", "Random Forest", "SVM"])
        st.markdown("The app expects a trained model bundle generated by `scripts/train.py`.")

    try:
        config, bundle = get_config_and_bundle(config_path, bundle_path)
    except Exception as exc:
        st.error(f"Could not load the config or model bundle: {exc}")
        st.info("Train the model first, then restart the app.")
        return

    audio_cfg = config["audio"]

    uploaded_file = st.file_uploader(
        "Upload audio", type=["wav", "mp3", "ogg", "flac", "m4a"]
    )

    demo_note = (
        "This is a reconstructed demo app based on the project paper's described pipeline, "
        "not the original production medical software."
    )
    st.info(demo_note)

    if uploaded_file is None:
        st.write("Upload an audio file to begin.")
        return

    audio_bytes = uploaded_file.getvalue()
    st.audio(audio_bytes)

    try:
        signal = load_uploaded_signal(
            uploaded_file,
            sample_rate=audio_cfg["sample_rate"],
            duration_seconds=audio_cfg["duration_seconds"],
        )
    except Exception as exc:
        st.error(f"Audio processing failed: {exc}")
        return

    if st.button("Run diagnosis", type="primary"):
        with st.spinner("Analyzing audio..."):
            try:
                pred_label, probabilities, features = predict_from_signal(
                    signal, config, bundle, model_name
                )
            except Exception as exc:
                st.error(f"Prediction failed: {exc}")
                return

        st.success(f"Predicted label: **{pred_label}**")

        col1, col2 = st.columns(2)
        with col1:
            st.pyplot(make_waveform_plot(signal, audio_cfg["sample_rate"]))
        with col2:
            st.pyplot(make_spectrogram_plot(signal, audio_cfg["sample_rate"]))

        st.subheader("Model output")
        if probabilities is not None:
            prob_df = make_probability_chart(bundle.classes_, probabilities)
            st.dataframe(prob_df, use_container_width=True)
        else:
            st.write("This model does not expose class probabilities.")

        st.subheader("Feature summary")
        feature_series = pd.Series(features.flatten())
        metrics = st.columns(4)
        metrics[0].metric("Feature count", int(feature_series.shape[0]))
        metrics[1].metric("Mean", f"{feature_series.mean():.4f}")
        metrics[2].metric("Std", f"{feature_series.std():.4f}")
        metrics[3].metric("Max", f"{feature_series.max():.4f}")

        with st.expander("Show extracted feature vector"):
            st.dataframe(pd.DataFrame({"feature_value": feature_series}), use_container_width=True)


if __name__ == "__main__":
    main()
